### ISSUE TITLE
Error when more than 4 users try to connect to a game

### ISSUE THREAD

**Issue by GraceJansen** [liberty-bikes/liberty-bikes#136]
When demo-ing this at the Festival of Innovation in Hursley we came across an issue where the countdown clock to a game would negative numbers if more than 4 players tried to connect to a game. Once we dropped this number and prevented more than 4 players from trying to play a single game at a time, the countdown reset from 3 and the game started at 0 (as expected)

**Comment by aguibert** [comment]
hi @GraceJansen, I tried to reproduce this issue locally but the queueing worked fine for me.  Can you describe a bit more what lead up to the error?  Was it consistently reproducible or was it a one-time issue?

When I did quick join (the "play now" button), 4 players joined a round and then when I joined with a 5th player they were placed into a new round, since a round ID was not specified.

When I did "join party" with a specific party code, players that joined while a round was in progress were placed in a queue, and when the round was over the first 4 players got moved into the next round, and the 5th person in queue got moved up to 1st in queue.

**Comment by GraceJansen** [comment]
Hi @aguibert, it only happened once during the conference but mainly because after it happened once we never let more than 4 people attempt to connect up at one time. The scenario was that 4 AI's were playing and whilst that game was occuring 5 people tried to connect. All of them were informed that they would be playing in the next game. The countdown started for this game - so, 3,2,1 and then when it hit zero instead of starting the next game it continued down into negative numbers (i.e.-1,-2,-3,-4) by the time I'd disconnected someone it was down at -18. This was all done with a specific party code. But yeah it did only happen once.

**Comment by mbroz2** [comment]
At a recent event we saw the same/similar bug, but only once in 3 hours and were unable to reproduce as well.
